In [1]:
import pandas as pd  ## 고수준 데이터 모델 (DataFrame) 모듈 pandas
c1 = pd.read_csv('class1.csv')
c2 = pd.read_csv('class2.csv')


In [2]:
c1

번호   이름  국어  영어  수학  과학
0   1   한돌  67  87  90  98
1   2   김신  45  45  56  98
2   4  이영호  95  59  96  88
3   4  박호일  65  94  89  98
4   5  조영구  45  65  78  98
5   6  장호일  78  76  98  89

In [3]:
c2

번호   이름   국어  영어  수학  과학
0   1  강교석   87  67  65  56
1   2  황유찬   89  98  78  78
2   3  유지명  100  78  56  65
3   4  송성필   99  89  87  87
4   5  주영훈   98  45  56  54
5   6  변정수   65  89  87  78

In [4]:
c1.수학.max(), c1.수학.mean()

(98, 84.5)

In [5]:
c2.수학.max(), c2.수학.mean()

(87, 71.5)

In [6]:
SUBJ = ['국어', '영어', '수학', '과학']

In [7]:
for s in SUBJ:
    if c1[s].mean() > c2[s].mean():
        print(s, '-->', '1반')
    else:
        print(s, '-->', '2반')

국어 --> 2반
영어 --> 2반
수학 --> 1반
과학 --> 1반


In [8]:
all_c = pd.concat([c1, c2]) # 칼럼 이어붙이기

In [9]:
all_c
# index 중복 현상
    

번호   이름   국어  영어  수학  과학
0   1   한돌   67  87  90  98
1   2   김신   45  45  56  98
2   4  이영호   95  59  96  88
3   4  박호일   65  94  89  98
4   5  조영구   45  65  78  98
5   6  장호일   78  76  98  89
0   1  강교석   87  67  65  56
1   2  황유찬   89  98  78  78
2   3  유지명  100  78  56  65
3   4  송성필   99  89  87  87
4   5  주영훈   98  45  56  54
5   6  변정수   65  89  87  78

In [10]:
c1['반'] = 1
c2['반'] = 2
# 학급 필드 합침

In [11]:
c1

번호   이름  국어  영어  수학  과학  반
0   1   한돌  67  87  90  98  1
1   2   김신  45  45  56  98  1
2   4  이영호  95  59  96  88  1
3   4  박호일  65  94  89  98  1
4   5  조영구  45  65  78  98  1
5   6  장호일  78  76  98  89  1

In [12]:
all_c = pd.concat([c1, c2])
all_c

번호   이름   국어  영어  수학  과학  반
0   1   한돌   67  87  90  98  1
1   2   김신   45  45  56  98  1
2   4  이영호   95  59  96  88  1
3   4  박호일   65  94  89  98  1
4   5  조영구   45  65  78  98  1
5   6  장호일   78  76  98  89  1
0   1  강교석   87  67  65  56  2
1   2  황유찬   89  98  78  78  2
2   3  유지명  100  78  56  65  2
3   4  송성필   99  89  87  87  2
4   5  주영훈   98  45  56  54  2
5   6  변정수   65  89  87  78  2

In [13]:
all_c = pd.concat([c1, c2], ignore_index=True) # index 새로 설정
all_c

번호   이름   국어  영어  수학  과학  반
0    1   한돌   67  87  90  98  1
1    2   김신   45  45  56  98  1
2    4  이영호   95  59  96  88  1
3    4  박호일   65  94  89  98  1
4    5  조영구   45  65  78  98  1
5    6  장호일   78  76  98  89  1
6    1  강교석   87  67  65  56  2
7    2  황유찬   89  98  78  78  2
8    3  유지명  100  78  56  65  2
9    4  송성필   99  89  87  87  2
10   5  주영훈   98  45  56  54  2
11   6  변정수   65  89  87  78  2

In [14]:
all_c.영어.describe()

count    12.000000
mean     74.333333
std      18.217541
min      45.000000
25%      63.500000
50%      77.000000
75%      89.000000
max      98.000000
Name: 영어, dtype: float64

In [15]:
# all_c['영어_norm'] = (영어점수 - 영어평균) / 영어표준편차
all_c['영어_norm'] = (all_c.영어 - all_c.영어.mean()) / all_c.영어.std() # data nomalize x-avrg/sts
all_c

번호   이름   국어  영어  수학  과학  반   영어_norm
0    1   한돌   67  87  90  98  1  0.695301
1    2   김신   45  45  56  98  1 -1.610170
2    4  이영호   95  59  96  88  1 -0.841680
3    4  박호일   65  94  89  98  1  1.079546
4    5  조영구   45  65  78  98  1 -0.512327
5    6  장호일   78  76  98  89  1  0.091487
6    1  강교석   87  67  65  56  2 -0.402542
7    2  황유찬   89  98  78  78  2  1.299114
8    3  유지명  100  78  56  65  2  0.201271
9    4  송성필   99  89  87  87  2  0.805085
10   5  주영훈   98  45  56  54  2 -1.610170
11   6  변정수   65  89  87  78  2  0.805085

In [18]:
all_c['영어_norm2'] = (all_c.영어 - all_c.영어.min()) / \
                     (all_c.영어.max() - all_c.영어.min()) # 0과 1사이로 구분 // 하위 0 ~ 상위1
all_c

번호   이름   국어  영어  수학  과학  반   영어_norm  영어_norm2
0    1   한돌   67  87  90  98  1  0.695301  0.792453
1    2   김신   45  45  56  98  1 -1.610170  0.000000
2    4  이영호   95  59  96  88  1 -0.841680  0.264151
3    4  박호일   65  94  89  98  1  1.079546  0.924528
4    5  조영구   45  65  78  98  1 -0.512327  0.377358
5    6  장호일   78  76  98  89  1  0.091487  0.584906
6    1  강교석   87  67  65  56  2 -0.402542  0.415094
7    2  황유찬   89  98  78  78  2  1.299114  1.000000
8    3  유지명  100  78  56  65  2  0.201271  0.622642
9    4  송성필   99  89  87  87  2  0.805085  0.830189
10   5  주영훈   98  45  56  54  2 -1.610170  0.000000
11   6  변정수   65  89  87  78  2  0.805085  0.830189

In [14]:
all_c[all_c.영어 > 90]

번호   이름  국어  영어  수학  과학  반
3   4  박호일  65  94  89  98  1
7   2  황유찬  89  98  78  78  2

In [15]:
all_c[ (all_c.영어 >= 90) & (all_c.수학 >= 80)] # 조건부 괄호

번호   이름  국어  영어  수학  과학  반
3   4  박호일  65  94  89  98  1

In [16]:
all_c.query('영어 >= 90 & 수학 >= 80')

번호   이름  국어  영어  수학  과학  반
3   4  박호일  65  94  89  98  1

In [17]:
all_c[all_c['영어'] > 90]

번호   이름  국어  영어  수학  과학  반
3   4  박호일  65  94  89  98  1
7   2  황유찬  89  98  78  78  2

In [18]:
# 컬럼 지정하기
all_c[all_c['영어'] > 90]['이름']

3    박호일
7    황유찬
Name: 이름, dtype: object

In [19]:
# 컬럼이 여러 개일때는 list로 지정해야 한다.
all_c[all_c['영어'] > 90][['이름', '영어', '반']]

이름  영어  반
3  박호일  94  1
7  황유찬  98  2

In [20]:
all_c[:2]

번호  이름  국어  영어  수학  과학  반
0   1  한돌  67  87  90  98  1
1   2  김신  45  45  56  98  1

In [21]:
all_c[0:10]

번호   이름   국어  영어  수학  과학  반
0   1   한돌   67  87  90  98  1
1   2   김신   45  45  56  98  1
2   4  이영호   95  59  96  88  1
3   4  박호일   65  94  89  98  1
4   5  조영구   45  65  78  98  1
5   6  장호일   78  76  98  89  1
6   1  강교석   87  67  65  56  2
7   2  황유찬   89  98  78  78  2
8   3  유지명  100  78  56  65  2
9   4  송성필   99  89  87  87  2

In [22]:
all_c.iloc[10]

번호      5
이름    주영훈
국어     98
영어     45
수학     56
과학     54
반       2
Name: 10, dtype: object

## pandas의 DataFrame, Series, Numpy의 ndarray

In [23]:
print(type(all_c))
print(type(all_c.수학))
print(type(all_c.수학.values))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>


In [24]:
print(all_c.max()) 
print()
print(all_c.수학.max())  # pandas,  df.max(), 
print(all_c.수학.values.max()) # np.max()

번호      6
이름    황유찬
국어    100
영어     98
수학     98
과학     98
반       2
dtype: object

98
98


In [25]:
all_c.values[:, 2:6]

array([[67, 87, 90, 98],
       [45, 45, 56, 98],
       [95, 59, 96, 88],
       [65, 94, 89, 98],
       [45, 65, 78, 98],
       [78, 76, 98, 89],
       [87, 67, 65, 56],
       [89, 98, 78, 78],
       [100, 78, 56, 65],
       [99, 89, 87, 87],
       [98, 45, 56, 54],
       [65, 89, 87, 78]], dtype=object)

In [26]:
all_c.iloc[0].values

array([1, '한돌', 67, 87, 90, 98, 1], dtype=object)

In [27]:
all_c.iloc[0].values.shape

(7,)

In [28]:
all_c.values

array([[1, '한돌', 67, 87, 90, 98, 1],
       [2, '김신', 45, 45, 56, 98, 1],
       [4, '이영호', 95, 59, 96, 88, 1],
       [4, '박호일', 65, 94, 89, 98, 1],
       [5, '조영구', 45, 65, 78, 98, 1],
       [6, '장호일', 78, 76, 98, 89, 1],
       [1, '강교석', 87, 67, 65, 56, 2],
       [2, '황유찬', 89, 98, 78, 78, 2],
       [3, '유지명', 100, 78, 56, 65, 2],
       [4, '송성필', 99, 89, 87, 87, 2],
       [5, '주영훈', 98, 45, 56, 54, 2],
       [6, '변정수', 65, 89, 87, 78, 2]], dtype=object)

In [29]:
all_c.values.shape[0]

12

In [30]:
all_c.번호.count()

12