In [1]:
import numpy as np  ## 백터, 행렬 데이터 전문 모듈 numpy
import pandas as pd  ## 고수준 데이터 모델 (DataFrame) 모듈 pandas
import matplotlib.pyplot as plt  ## 차트 그리기 모듈 matplotlib
df = pd.read_csv('class1.csv', encoding='utf-8') # df : data frame 
# Data Frame - sheet class
# Series - column class

print('칼럼이름들', list(df.columns) ) 

print(df)


칼럼이름들 ['번호', '이름', '국어', '영어', '수학', '과학']
   번호   이름  국어  영어  수학  과학
0   1   한돌  67  87  90  98
1   2   김신  45  45  56  98
2   3  이영호  95  59  96  88
3   4  박호일  65  94  89  98
4   5  조영구  45  65  78  98
5   6  장호일  78  76  98  89


In [2]:
df

번호   이름  국어  영어  수학  과학
0   1   한돌  67  87  90  98
1   2   김신  45  45  56  98
2   3  이영호  95  59  96  88
3   4  박호일  65  94  89  98
4   5  조영구  45  65  78  98
5   6  장호일  78  76  98  89

In [3]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [4]:
list(df.index)

[0, 1, 2, 3, 4, 5]

In [5]:
df.values # numpy array  형태

array([[1, '한돌', 67, 87, 90, 98],
       [2, '김신', 45, 45, 56, 98],
       [3, '이영호', 95, 59, 96, 88],
       [4, '박호일', 65, 94, 89, 98],
       [5, '조영구', 45, 65, 78, 98],
       [6, '장호일', 78, 76, 98, 89]], dtype=object)

In [6]:
type(df.values) # 판다스 데이터를 numpy로 변환 (서로 변환가능)

numpy.ndarray

In [7]:
df.values[0, 2:] # 한돌의 과목별 점수 # 0번행의 2번칼럼

array([67, 87, 90, 98], dtype=object)

In [8]:
df

번호   이름  국어  영어  수학  과학
0   1   한돌  67  87  90  98
1   2   김신  45  45  56  98
2   3  이영호  95  59  96  88
3   4  박호일  65  94  89  98
4   5  조영구  45  65  78  98
5   6  장호일  78  76  98  89

In [9]:
total = df.values[0, 2:].sum() # 한돌의 평균 점수
print('%s: %d, %.1f' % (df.values[0, 1], total, total/4))

한돌: 342, 85.5


In [10]:
np.sum(df.values[:, 2:], axis = 1)

array([342, 244, 338, 346, 286, 341], dtype=object)

In [14]:
np.sum(df.values[:, 2:], axis=0)

array([395, 426, 507, 569], dtype=object)

In [12]:
np.sum(df.values[:, 2:], axis = 0)

array([395, 426, 507, 569], dtype=object)

In [8]:
print(list(df.index))

[0, 1, 2, 3, 4, 5]


In [10]:
df.국어.sum()

395

In [24]:
df['국어']
kuk = df[['국어']]
print(type(kuk))

<class 'pandas.core.frame.DataFrame'>


In [25]:
kuk

국어
0  67
1  45
2  95
3  65
4  45
5  78

In [22]:
df['국어']
kuk = df[['국어','수학']]
print(type(kuk))

<class 'pandas.core.frame.DataFrame'>


In [23]:
kuk

국어  수학
0  67  90
1  45  56
2  95  96
3  65  89
4  45  78
5  78  98

In [29]:
df[1:3] # 범위 지정은 가능 , but 특정 행은 불가능 ex) df[1]

번호   이름  국어  영어  수학  과학
1   2   김신  45  45  56  98
2   3  이영호  95  59  96  88

In [33]:
df2 = df.sort_values(by='이름')
df2

번호   이름  국어  영어  수학  과학
1   2   김신  45  45  56  98
3   4  박호일  65  94  89  98
2   3  이영호  95  59  96  88
5   6  장호일  78  76  98  89
4   5  조영구  45  65  78  98
0   1   한돌  67  87  90  98

In [34]:
df2[0:2]

번호   이름  국어  영어  수학  과학
1   2   김신  45  45  56  98
3   4  박호일  65  94  89  98

In [16]:
df.sum()

번호                  21
이름    한돌김신이영호박호일조영구장호일
국어                 395
영어                 426
수학                 507
과학                 569
dtype: object

In [44]:
df2.loc[1:5] # location # index value에 따른 출력 #현재 sort한 기준

번호   이름  국어  영어  수학  과학
1   2   김신  45  45  56  98
3   4  박호일  65  94  89  98
2   3  이영호  95  59  96  88
5   6  장호일  78  76  98  89

In [42]:
df2.iloc[1:5] # lnteger location # index value 관계 없이 출력

번호   이름  국어  영어  수학  과학
3   4  박호일  65  94  89  98
2   3  이영호  95  59  96  88
5   6  장호일  78  76  98  89
4   5  조영구  45  65  78  98

In [17]:
df.head()

번호   이름  국어  영어  수학  과학
0   1   한돌  67  87  90  98
1   2   김신  45  45  56  98
2   3  이영호  95  59  96  88
3   4  박호일  65  94  89  98
4   5  조영구  45  65  78  98

In [11]:
kuk = df[['국어']]
print(type(kuk))


<class 'pandas.core.frame.DataFrame'>


In [18]:
df.describe()

번호         국어         영어         수학         과학
count  6.000000   6.000000   6.000000   6.000000   6.000000
mean   3.500000  65.833333  71.000000  84.500000  94.833333
std    1.870829  19.333046  18.253767  15.617298   4.915960
min    1.000000  45.000000  45.000000  56.000000  88.000000
25%    2.250000  50.000000  60.500000  80.750000  91.250000
50%    3.500000  66.000000  70.500000  89.500000  98.000000
75%    4.750000  75.250000  84.250000  94.500000  98.000000
max    6.000000  95.000000  94.000000  98.000000  98.000000

In [12]:
df[0:5]
df['국어']

0    67
1    45
2    95
3    65
4    45
5    78
Name: 국어, dtype: int64

In [15]:
print(type(df.loc[5]))
print(df.loc[5])

<class 'pandas.core.series.Series'>
번호      6
이름    장호일
국어     78
영어     76
수학     98
과학     89
Name: 5, dtype: object


In [14]:
print(type(df.iloc[5]))
print(df.iloc[5])

<class 'pandas.core.series.Series'>
번호      6
이름    장호일
국어     78
영어     76
수학     98
과학     89
Name: 5, dtype: object


### 조건으로 필터링하기

In [45]:
df[df.국어 >= 70]

번호   이름  국어  영어  수학  과학
2   3  이영호  95  59  96  88
5   6  장호일  78  76  98  89

In [46]:
df[(df.국어 >= 70) | (df.영어 >= 70)] # and, or 할때는 괄호 표시

번호   이름  국어  영어  수학  과학
0   1   한돌  67  87  90  98
2   3  이영호  95  59  96  88
3   4  박호일  65  94  89  98
5   6  장호일  78  76  98  89

In [47]:
df.query("국어 >= 70 & 영어 >= 70") # db query와 비슷

번호   이름  국어  영어  수학  과학
5   6  장호일  78  76  98  89

In [48]:
df[['국어', '영어']]

국어  영어
0  67  87
1  45  45
2  95  59
3  65  94
4  45  65
5  78  76

In [49]:
subjects = ['국어', '영어', '수학', '과학']

df[subjects].sum(axis=0) # 각 행 합계
print(df[subjects].sum(axis=0))
num_st = df.국어.count() #정상값만 count//null 값 X
print(df[subjects].sum(axis=0) / num_st)
print(df[subjects].max(axis=0)) #과목별 최고점



국어    395
영어    426
수학    507
과학    569
dtype: int64
국어    65.833333
영어    71.000000
수학    84.500000
과학    94.833333
dtype: float64
국어    95
영어    94
수학    98
과학    98
dtype: int64


In [55]:
df['개인별과목합'] = df[subjects].sum(axis=1) # 각 열 계산
df['개인별평균'] = df['개인별과목합'] / len(subjects)
df['개인별최고점'] = df[subjects].max(axis=1)
df

번호   이름  국어  영어  수학  과학   총점     평균  최고점  개인별과목총점  개인별평균  개인별최고점  개인별과목합
0   1   한돌  67  87  90  98  342  85.50   98      342  85.50      98     342
1   2   김신  45  45  56  98  244  61.00   98      244  61.00      98     244
2   3  이영호  95  59  96  88  338  84.50   96      338  84.50      96     338
3   4  박호일  65  94  89  98  346  86.50   98      346  86.50      98     346
4   5  조영구  45  65  78  98  286  71.50   98      286  71.50      98     286
5   6  장호일  78  76  98  89  341  85.25   98      341  85.25      98     341

In [ ]:
#df[['수학']]
print(type(df.수학))
print(type(df['수학']))
print(type(df[['수학']]))

In [56]:
print('=== 성적순')
df2 = df.sort_values(['영어', '수학'], ascending=[False, False])

df2


=== 성적순


번호   이름  국어  영어  수학  과학   총점     평균  최고점  개인별과목총점  개인별평균  개인별최고점  개인별과목합
3   4  박호일  65  94  89  98  346  86.50   98      346  86.50      98     346
0   1   한돌  67  87  90  98  342  85.50   98      342  85.50      98     342
5   6  장호일  78  76  98  89  341  85.25   98      341  85.25      98     341
4   5  조영구  45  65  78  98  286  71.50   98      286  71.50      98     286
2   3  이영호  95  59  96  88  338  84.50   96      338  84.50      96     338
1   2   김신  45  45  56  98  244  61.00   98      244  61.00      98     244

In [60]:
print('=== 성적순')
df2 = df.sort_values(by='개인별총합', assending=[True])

df2

=== 성적순


TypeError: sort_values() got an unexpected keyword argument 'assending'

In [58]:
# 완전 새롭게 index reset, 정렬
df2.reset_index(inplace=True, drop=True) 
df2

번호   이름  국어  영어  수학  과학   총점     평균  최고점  개인별과목총점  개인별평균  개인별최고점  개인별과목합
0   4  박호일  65  94  89  98  346  86.50   98      346  86.50      98     346
1   1   한돌  67  87  90  98  342  85.50   98      342  85.50      98     342
2   6  장호일  78  76  98  89  341  85.25   98      341  85.25      98     341
3   5  조영구  45  65  78  98  286  71.50   98      286  71.50      98     286
4   3  이영호  95  59  96  88  338  84.50   96      338  84.50      96     338
5   2   김신  45  45  56  98  244  61.00   98      244  61.00      98     244

In [61]:
df2
df2.drop(['총점'], axis=1, inplace=True) # calumn delete
df2

번호   이름  국어  영어  수학  과학     평균  최고점  개인별과목총점  개인별평균  개인별최고점  개인별과목합
0   4  박호일  65  94  89  98  86.50   98      346  86.50      98     346
1   1   한돌  67  87  90  98  85.50   98      342  85.50      98     342
2   6  장호일  78  76  98  89  85.25   98      341  85.25      98     341
3   5  조영구  45  65  78  98  71.50   98      286  71.50      98     286
4   3  이영호  95  59  96  88  84.50   96      338  84.50      96     338
5   2   김신  45  45  56  98  61.00   98      244  61.00      98     244

In [62]:
df2[['이름', '평균']]

이름     평균
0  박호일  86.50
1   한돌  85.50
2  장호일  85.25
3  조영구  71.50
4  이영호  84.50
5   김신  61.00

In [65]:
df2.to_csv('sorted_class1_gto.csv', encoding='utf-8', index=False) #save file

In [66]:
df2.to_csv('sorted_class1_gto.csv', encoding='utf-8', index=True) #